# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-09 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbcommentanalysis',
            name='item_name',
            field=models.CharField(max_length=200, verbose_name='\u6dd8\u5b9d\u5e97\u94fa\u5546\u54c1\u7684\u540d\u79f0'),
        ),
        migrations.AlterField(
            model_name='tbcommentanalysis',
            name='product_id',
            field=models.BigIntegerField(verbose_name='\u6dd8\u5b9d\u5546\u54c1\u7684 id'),
        ),
        migrations.AlterField(
            model_name='tbvisit',
            name='tb_url',
            field=models.CharField(default='', max_length=200, verbose_name='\u6dd8\u5b9d\u5e97\u94fa\u5546\u54c1\u7684 url \u94fe\u63a5'),
        ),
    ]
